# Generated by Django 4.1.3 on 2022-11-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='симптом')),
                ('doctor', models.CharField(max_length=50, verbose_name='лечащий врач')),
            ],
        ),
    ]
