# Generated by Django 4.1.3 on 2022-12-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_clinic_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReceipt', models.DateField(verbose_name='дата поступления')),
                ('dateDischarge', models.DateField(verbose_name='дата выписки')),
                ('status', models.IntegerField(max_length=8, verbose_name='статус пользователя')),
            ],
        ),
    ]
