# Generated by Django 4.1.3 on 2022-12-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.IntegerField(verbose_name='статус пользователя'),
        ),
    ]
